[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--build-id=none",
    "-C", "target-cpu=cortex-a53",
    "-C", "link-arg=--no-undefined-version",
    "-C", "link-arg=--no-rosegment"
]